version: 1.0.{build}
os: Visual Studio 2019

environment:
  matrix:
  - ARCH: x86

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 16 2019" -A x64 ..
- cmake --build . --target unit --verbose --config Debug
- cmake --build . --target unit --verbose --config Release

test_script:
- set OLDPATH=%PATH%
- set PATH=C:\projects\tts\build\src\Release;%PATH%
- ctest -C Release -VV
- set PATH=C:\projects\tts\build\src\Debug;%OLDPATH%
- ctest -C Debug   -VV
