version: 2.0
jobs:
  gcc-8:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Ninja
          command: 'apt-get update && sudo apt-get install -y ninja-build'
      - run:
          name: Building tests
          command: g++ --version && mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja
      - run: cd build && ninja unit -j 8
      - run: cd build && ctest -j 8

  gcc-7:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Ninja
          command: 'apt-get update && sudo apt-get install -y ninja-build'
      - run:
          name: Building tests
          command: g++ --version && mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja
      - run: cd build && ninja unit -j 8
      - run: cd build && ctest -j 8

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-8
      - gcc-7
