version: 2.0

jobs:
  gcc-8:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: . .circleci/prepare.sh
      - run:
          name: Running tests
          command: . .circleci/run.sh

  gcc-7:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: . .circleci/prepare.sh
      - run:
          name: Running tests
          command: . .circleci/run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-8
      - gcc-7
